# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativeStructure' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   pod 'Firebase/Auth'
   pod ‘Firebase/Core’
   pod ‘Firebase’
   pod ‘Firebase/Messaging’
   pod  ‘Firebase/Database’

  # Pods for reactNativeStructure

  target 'reactNativeStructure-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

    pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  end

  target 'reactNativeStructureTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeStructure-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeStructure-tvOS

end
